name: Deploy Website

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 12.0
      - run: npm install -g surge
      - run: surge ./ letter-v1.surge.sh --token ${{ secrets.SURGE_TOKEN }}
