name: "Deploy site to Netlify"

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
